name: Build

on:
  push:

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev libglu1-mesa-dev libxkbcommon-dev libxcb-cursor-dev p7zip-full
    - name: Install Qt
      uses: ./.github/actions/download-qt
      with:
        toolchain: gcc_64
        components: qtbase icu
    - name: Install Qbs
      uses: ./.github/actions/download-qbs
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Conan
      uses: turtlebrowser/get-conan@main
    - name: Configure Conan remote
      run: conan remote update conancenter --url="https://center2.conan.io"
    - name: Setup Conan profiles
      run: ./scripts/setup-conan-profiles.sh --toolchain gcc_64
    - name: Patch Conan QbsDeps
      run: ./scripts/patch-conan-qbsdeps.sh
    - name: Setup Qbs
      run: |
        qbs setup-toolchains --detect
        qbs setup-qt $(which qmake) qt
        qbs config defaultProfile qt
        qbs config --list
    - name: Build
      run: |
        qbs resolve project.conanProfile:ci config:release
        qbs build config:release

  build-macos:
    name: Build on macOS
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: ./.github/actions/download-qt
      with:
        toolchain: clang_64
    - name: Install Qbs
      uses: ./.github/actions/download-qbs
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Conan
      uses: turtlebrowser/get-conan@main
    - name: Configure Conan remote
      run: conan remote update conancenter --url="https://center2.conan.io"
    - name: Setup Conan profiles
      run: ./scripts/setup-conan-profiles.sh --toolchain clang_64
    - name: Patch Conan QbsDeps
      run: ./scripts/patch-conan-qbsdeps.sh
    - name: Setup Qbs
      run: |
        qbs setup-toolchains --detect
        qbs setup-qt --detect
        qbs config profiles.qt.baseProfile xcode_13_2_1-macosx-x86_64
        qbs config defaultProfile qt
        qbs config --list
    - name: Build
      run: |
        qbs resolve project.conanProfile:ci config:release
        qbs build config:release

  build-windows:
    name: Build on Windows
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: ./.github/actions/download-qt
      with:
        toolchain: win64_msvc2022_64
    - name: Install Qbs
      uses: ./.github/actions/download-qbs
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Conan
      uses: turtlebrowser/get-conan@main
    - name: Configure Conan remote
      run: conan remote update conancenter --url="https://center2.conan.io"
      shell: bash
    - name: Setup Conan profiles
      run: ./scripts/setup-conan-profiles.sh --toolchain msvc_64
      shell: bash
    - name: Patch Conan QbsDeps
      run: ./scripts/patch-conan-qbsdeps.sh
      shell: bash
    - name: Setup Qbs
      run: |
        qbs setup-toolchains --detect
        qbs setup-qt $(which qmake).exe qt
        qbs config profiles.qt.baseProfile MSVC2022-1-x86_x64
        qbs config defaultProfile qt
        qbs config --list
      shell: bash
    - name: Build
      run: |
        qbs resolve project.conanProfile:ci config:release
        qbs build config:release
      shell: bash
